layout_spectrum: 0.4647993
typography_spectrum: 0.4013482
color:
  saturation: 0.1729811
  lightness: 0.5574064
  brandStrength: 0.07782877
  rhythmicContrast: 0.522596
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Kevin Canavan
